### ISSUE TITLE
bash should also be installed

### ISSUE THREAD

**Issue by silmaril42** [ConorBeh/iocage-plugin-gitea#1]
I just installed the Gitea plugin on my FreeNAS server - works great!

I ran into a little problem:
- create new repository in gitea without initializing it
  - commands for pushing an existing repo are shown.
- try to run those commands
  - `git remote add origin ...` works fine
  - `git push -u origin master` runs into an error
```
remote: env: bash: No such file or directory
To http://gitea:3000/...
 ! [remote rejected] master -> master (pre-receive hook declined)
```
I was able to solve this by running the following command inside the gitea jail:
```
pkg install bash
```
Maybe this should be done during plugin installation?

**Comment by ConorBeh** [comment]
Thanks for reporting this. I'll add bash as a PKG to be installed.

**Comment by ConorBeh** [comment]
Fixed by https://github.com/ix-plugin-hub/iocage-plugin-index/pull/50

Thanks.
