### ISSUE TITLE
ssh is not enabled

### ISSUE THREAD

**Issue by tprelog** [ConorBeh/iocage-plugin-gitea#3]
Hi - I was giving Gitea a try (currently I'm using Gogs) however I am not able to `git` anything over ssh

I found that `sshd` has not been enabled

After running the following commands from the jail's console, I was able to use `git` over ssh

```bash
sysrc sshd_enable="YES"
service sshd start
```

Please consider adding these lines to your `post_install.sh`

**Comment by ConorBeh** [comment]
I'll add that. Thanks for the suggestion.

**Comment by ConorBeh** [comment]
Fixed by https://github.com/ConorBeh/iocage-plugin-gitea/commit/8a3503a9ab64c86bacb2fe2f74ea40c5fc14144b
